"""Module for analyzing model performance using a confusion matrix.

This module provides a function to calculate and potentially plot a confusion matrix
based on the model's predictions and the ground truth labels of a test set.
It also identifies and counts misclassified instances.
"""

import numpy as np
import tensorflow as tf


def plot_confusion_matrix(test_labels_set, test_blend_set, test_index_set, predictions):
    """
    Calculates and processes the confusion matrix for model predictions against ground truth.

    This function takes the true labels, predicted labels, and other test set information
    to compute a confusion matrix. It also identifies misclassified images and counts
    the number of errors per ground truth class.

    Args:
        test_labels_set (list or np.array): List or array of the one-hot encoded ground truth labels for the test set.
        test_blend_set (list or np.array): List or array of the blendshapes features for the test set.
        test_index_set (list): List of the original indices of the test set images.
        predictions (list): List of the predicted class labels (integers) generated by the trained model.

    Note:
        This function currently calculates the confusion matrix and error counts but does not
        explicitly plot it. The name `plot_confusion_matrix` might be a misnomer given its current
        implementation, which focuses on calculation and error identification.
    """
    errors_count = {"0": 0, "1": 0, "2": 0} # Dictionary to count misclassifications per true class
    ground_truth = [] # List to store integer ground truth labels
    errors = []       # List to store indices of misclassified images

    # Convert one-hot encoded ground truth labels to integer labels
    for i in test_labels_set:
        i = np.argmax(i)
        ground_truth.append(i)
    
    # Identify misclassified images by comparing predictions with ground truth
    for j in range(len(test_blend_set)):
        if predictions[j] != ground_truth[j]:     # Check if the predicted label differs from the ground truth
            errors.append(test_index_set[j])      # Add the index of the misclassified image to the errors list
    
    # Create the confusion matrix using TensorFlow
    confusion_matrix = tf.math.confusion_matrix(
        ground_truth,
        predictions,
        num_classes=3, # Assuming 3 classes (0, 1, 2)
        dtype=tf.dtypes.int32,
    )
    # The confusion_matrix variable now holds the computed matrix.
    # print(confusion_matrix) # Uncomment to print the confusion matrix

    # Count misclassifications for each ground truth class
    for i in range(len(predictions)): # Iterate through predictions (assuming same length as ground_truth)
        if predictions[i] == ground_truth[i]:
            continue # Skip if prediction is correct
        elif predictions[i] != ground_truth[i]:
            # Increment error count for the true class of the misclassified image
            errors_count[str(ground_truth[i])] = errors_count[str(ground_truth[i])] + 1
    # The errors_count dictionary now holds the number of misclassifications for each true class.
    # print(errors_count) # Uncomment to print the error counts
